---
name: new-version-deploy

run-name: Merge ${SRC_BRANCH} with ${DEST_BRANCH}

on:
  push:
    branches:
      - 'feature/deploy-actions'

env:
  SRC_BRANCH: 'feature/deploy-actions'
  DEST_BRANCH: 'media'

jobs:
  deploy:
    runs-on: ["linux"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check if ${DEST_BRANCH} branch exist and create
        run: |
          # Check if ${DEST_BRANCH} branch exist
          if [[ -z $(git ls-remote --heads origin "${DEST_BRANCH}") ]]; then
            git checkout -b "${DEST_BRANCH}"
          else
            git merge --no-ff "${DEST_BRANCH}"
            git checkout "${DEST_BRANCH}"
          fi
          git merge --no-ff "${SRC_BRANCH}"
          git push origin "${DEST_BRANCH}"
