---
name: runner-deploy

run-name: Merge main with media

on:
  push:
    branches:
      - 'feature/deploy-actions'


jobs:
  deploy:
    runs-on: ["linux"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check if media branch exist and create
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        working-directory: runner
        run: |
          if git show-ref --verify --quiet "refs/heads/media"; then
            git checkout media
          else
            git checkout -b media
          fi
          git merge feature/deploy-actions
          git push origin media
