---
name: new-version-deploy

run-name: Merge main with media

on:
  push:
    branches:
      - 'feature/deploy-actions'

env:
  SRC_BRANCH: 'feature/deploy-actions'
  DEST_BRANCH: 'media'

jobs:
  deploy:
    runs-on: ["linux"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check if media branch exist and create
        run: |
          # Check if ${DEST_BRANCH} branch exist
          if [[ -z $(git ls-remote --heads origin "${DEST_BRANCH}") ]]; then
            git checkout -b "${DEST_BRANCH}"
          else
            echo "cehck"
            git checkout "${DEST_BRANCH}"
          fi
          echo "hola"
          git pull origin "${SRC_BRANCH}" -X theirs
          echo "Test"
          git push origin "${DEST_BRANCH}"
