---
name: runner-deploy

run-name: Merge main with media

on:
  push:
    branches:
      - 'feature/deploy-actions'


jobs:
  deploy:
    runs-on: ["linux"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check if media branch exist and create
        run: |
          if git show-ref --verify --quiet "refs/heads/media"; then
            git checkout media
            git fetch
            echo "fetch"
          else
            echo "Not exist"
            git checkout -b media
          fi
          git merge feature/deploy-actions
          echo "push"
          git push origin media
