---
name: new-version-deploy

run-name: Merge main with media

on:
  push:
    branches:
      - 'feature/deploy-actions'

env:
  SRC_BRANCH: 'feature/deploy-actions'
  DEST_BRANCH: 'media'
  SCM_USER: ${{ secrets.SCM_USER }}
  SCM_EMAIL: ${{ secrets.SCM_EMAIL }}

jobs:
  deploy:
    runs-on: ["ubuntu-22.04"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Config git
        run: |
          # echo ${GPG_KEY} | gpg --import
          git config --local user.name "${SCM_USER}"
          git config --local user.email "${SCM_EMAIL}"
          # git config --local commit.gpgsign true

      - name: Check if media branch exist and create
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Check if ${DEST_BRANCH} branch exist
          if [[ -z $(git ls-remote --heads origin "${DEST_BRANCH}") ]]; then
            git checkout -b "${DEST_BRANCH}"
          else
            git checkout "${DEST_BRANCH}"
          fi
          git merge "${SRC_BRANCH}" # github.head or ref
          git push origin "${DEST_BRANCH}"
