---
name: runner-deploy

run-name: Merge main with media

on:
  push:
    branches:
      - 'feature/deploy-actions'


jobs:
  deploy:
    runs-on: ["linux"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check if media branch exist and create
        run: |
          echo $(git branch --list media)
          echo $(git ls-remote --heads origin media)
          if [[ -z $(git ls-remote --heads origin media) ]]; then
            echo "Not exist"
            git checkout -b media
          else
            echo "Exist"
            git checkout media
            git pull
          fi
          git merge feature/deploy-actions
          echo "push"
          git push origin media
