---
name: pack-add-imported

run-name: Add imported packs ${{ inputs.pack-ids }}...

on:
  workflow_dispatch:
    inputs:
      pack-ids:
        description: "Pack IDs separate with white space"
        required: true

  workflow_call:
    inputs:
      pack-ids:
        description: "Pack IDs separate with white space"
        required: true
        type: string


jobs:
  add-image:
    runs-on: ["ubuntu-latest"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: pages

      - name: Install poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -

      - name: Import packs
        run: |
          poetry install
          poetry run \
            pack \
            add-imported \
            "${{ inputs.pack-ids }}"

      - name: Config git
        env:
          SCM_USER: ${{ secrets.SCM_USER }}
          SCM_EMAIL: ${{ secrets.SCM_EMAIL }}
        run: |
          git config --local user.name "${SCM_USER}"
          git config --local user.email "${SCM_EMAIL}"

      - name: Commit changes
        env:
          GITHUB_TOKEN: ${{ secrets.GH_SCM_TOKEN }}
        run: |
          git add .
          git commit -m "feat: Add imported packs ${{ inputs.pack-ids }}"
          git push
